# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-28 20:27
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=200)),
                ('message', models.CharField(max_length=500)),
                ('timestamp', models.DateTimeField(default=datetime.datetime(2017, 5, 28, 20, 27, 24, 134861))),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
