# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-01 17:40
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0004_auto_20170601_1729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactus',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2017, 6, 1, 17, 40, 55, 500065)),
        ),
    ]
