# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-09 12:52
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_cart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppingcart',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2017, 6, 9, 12, 52, 33, 616796, tzinfo=utc), editable=False),
        ),
    ]
