# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-27 07:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField()),
                ('description', models.CharField(blank=True, max_length=300, null=True)),
                ('image1', models.ImageField(blank=True, null=True, upload_to='product_images')),
            ],
        ),
    ]
