# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-27 20:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20170527_1926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
